name: Laravel

on:
  push:
    branches: [ "refactor", "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker compose build app

    - name: Copy .env
      run: |
        docker compose run --rm \
          --entrypoint sh app -c "cp .env.example .env || true"

    - name: Install dependencies
      run: |
        docker compose run --rm \
          --entrypoint sh app -c "composer install --no-interaction --prefer-dist"

    - name: Generate app key
      run: |
        docker compose run --rm \
          --entrypoint sh app -c "php artisan key:generate"

    - name: Set permissions
      run: |
        docker compose run --rm \
          --entrypoint sh app -c "chmod -R 777 storage bootstrap/cache"

    - name: Create SQLite database
      run: |
        docker compose run --rm \
          --entrypoint sh app -c "
            mkdir -p database &&
            touch database/database.sqlite
          "

    - name: Run tests
      run: |
        docker compose run --rm \
          --entrypoint sh app -c "php artisan test"
